language: node_js
node_js:
  - 6
branches:
  only:
    - master

cache:
  directories:
    - node_modules

# 配置环境
before_install:
  # 替换为刚才生成的解密信息
  - openssl aes-256-cbc -K $encrypted_9aea50574292_key -iv $encrypted_9aea50574292_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # 配置 git 替换为自己的信息
  - git config --global user.name 'jimmy.m.gong'
  - git config --global user.email jimmy.m.gong@gmail.com

# 安装依赖
install:
  - npm install hexo-cli -g
  - npm install
  # - git clone https://github.com/yssource/hexo-theme-next.git themes/next

# 部署的命令
script:
  # - npm run deploy  # hexo clean && hexo g -d
  hexo clean && hexo g -d
  # - hexo generate && rsync -az -vv --delete -e 'ssh -p 1224' public/ brook@uedsky.com:/home/jimmy/org/blog

# addons:
#   ssh_known_hosts: uedsky.com:1224
