language: node_js
node_js: stable

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
# packages:
#   - emacs25

# 配置环境
# before_install:
#   # 替换为刚才生成的解密信息
#   - openssl aes-256-cbc -K $encrypted_9aea50574292_key -iv $encrypted_9aea50574292_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
#   # 改变文件权限
#   - chmod 600 ~/.ssh/id_rsa
#   # 配置 ssh
#   - eval $(ssh-agent)
#   - ssh-add ~/.ssh/id_rsa
#   - cp .travis/ssh_config ~/.ssh/config
#   # 配置 git 替换为自己的信息
#   - git config --global user.name 'jimmy.m.gong'
#   - git config --global user.email jimmy.m.gong@gmail.com

# 配置环境
before_install:
  # # Configure $PATH: Executables are installed to $HOME/bin
  # - export PATH="$HOME/bin:$PATH"
  # # Download the makefile to emacs-travis.mk
  # - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # # Install Emacs (according to $EMACS_VERSION) and Cask
  # - make -f emacs-travis.mk install_emacs
  # - make -f emacs-travis.mk install_cask
  # # Install Texinfo, if you need to build info manuals for your project
  # # - make -f emacs-travis.mk install_texinfo
  - emacs --version
  - chmod a+x ./e25.sh
  # - bash -xv ./e25.sh

  # - sudo apt-get purge emacs-snapshot-common emacs-snapshot-bin-common emacs-snapshot emacs-snapshot-el emacs-snapshot-gtk emacs23 emacs23-bin-common emacs23-common emacs23-el emacs23-nox emacs23-lucid auctex emacs24 emacs24-bin-common emacs24-common
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update
  - sudo apt-get install -y emacs-snapshot emacs-snapshot-el

  # - # sudo apt-get purge emacs emacs23
  # - sudo apt-get remove --auto-remove emacs23-lucid emacs23-nox
  # - wget http://ftpmirror.gnu.org/emacs/emacs-25.1.tar.xz
  # - tar xf emacs-25.1.tar.xz
  # - cd emacs-25.1
  # - sudo apt-get build-dep -y emacs24
  # - sudo apt-get install -y libwebkitgtk-3.0-dev
  # - ./configure --with-xwidgets --with-x-toolkit=gtk3 --with-modules
  # - make -j5
  # - sudo make install

  # - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  # - sudo apt-get install chktex

  # - cask install
  - which emacs
  - emacs --version
  - emacs --help

  - ls -al /etc/emacs/site-start.d
  - ls -al /etc/emacs/

# 安装依赖
install:
  - npm install hexo-cli -g
  # - npm install https://github.com/CodeFalling/hexo-renderer-org#emacs --save
  # - rm -rfv ./node_modules/*
  - rm -rfv ./node_modules/hexo-renderer-org/*
  - npm install
  - ls -al ./node_modules/
  - nl ./node_modules/hexo-renderer-org/.travis.yml
  # - git clone https://github.com/yssource/hexo-theme-next.git themes/next

# 部署的命令
script:
  # - npm run deploy  # hexo clean && hexo g -d
  # - cask exec ert-runner
  # - hexo clean && hexo g -d
  # - hexo clean && hexo g
  # - emacs /home/travis/build/yssource/yssource.github.io/source/_posts/222.org --batch --kill -l /home/travis/build/yssource/yssource.github.io/node_modules/hexo-renderer-org/lib/tmp.el
  - emacs /home/travis/build/yssource/yssource.github.io/source/_posts/222.org --batch --kill -l /home/travis/build/yssource/yssource.github.io/tmp.el
  - nl /home/travis/build/yssource/yssource.github.io/node_modules/hexo-renderer-org/lib/tmp.el
  - nl /home/travis/build/yssource/yssource.github.io/node_modules/hexo-renderer-org/lib/renderer.js
  # - hexo g
  - hexo clean && hexo g
  # - hexo generate && rsync -az -vv --delete -e 'ssh -p 1224' public/ jimmy@google.com:/home/jimmy/org/blog

# addons:
#   ssh_known_hosts: uedsky.com:1224

after_script:
  - cd ./public
  - git init
  # 配置 git 替换为自己的信息
  - git config user.name 'JimmyG'
  - git config user.email jimmy.m.gong@gmail.com
  - git add -A .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

env:
 global:
  - GH_REF: github.com/yssource/yssource.github.io.git
  # - EMACS: emacs25
  - EMACS_VERSION=snapshot
