#+STARTUP: indent
#+TITLE: jiehun
#+AUTHOR: Jimmy m Gong
#+EMAIL: yssource@163.com
#+LANGUAGE: zh-Hans
#+OPTIONS: H:3 num:t toc:nil \n:t ::t |:t ^:nil -:nil f:t *:t <:t html-postamble:nil
#+URI: /blog/%y/%m/%d/
#+DATE: 2016-11-03
#+LAYOUT: post
#+TAGS:
#+CATEGORIES:
#+DESCRIPTON:

* 时间:
  - 公历: 2017-01-06 星期五
  - 农历: 2016年12月9号 腊月初九
* 姓名:
- 新郎: 龚敏
- 新娘: 戴莹莹

* 仪式名称:
结婚典礼
* 地点:
修水珠江大酒店
* 席设:
修水珠江大酒店
* 席设时间:
正午 12:00
* 敬邀人:
龚著旺 陈秀良



此时此刻我的心情是万分的激动与开心，因为今天我和戴莹莹结婚了。一时间纵有千言万语却不知从和说起。但我知道，这万语千言最终只能汇聚成两个字，那就是“感谢”。首先要感谢在座的各位领导及亲朋好友和各位来宾、特别是道道全粮油集团刘董事长及公司各位领导. 其次我要感谢我的父亲、母亲 ，感谢你们给予了我生命 ，教育我成人。今天儿子长大了，儿子结婚了。没有你们就没有我今天 ，你们二老辛苦了 ，让儿子在这里给你们深深的鞠上一躬吧。再次我要感谢莹莹爸爸、妈妈 ，我的岳父岳母。感谢你们将唯一的一颗掌上明珠交付给我保管。我绝对不会辜负你们对我的信任。也许这辈子我无法让您的女儿成为世界上最富有的女人，但我会凭着一双勤劳的双手使她成为世界上最幸福的女人。最后，衷心的祝愿各位所有到场的亲朋好友永远健康快乐，谢谢 。粗茶淡饭 ，不成敬意。大家吃好喝好 ！！！

*** 结婚致辞
尊敬的各位来宾：大家好！

今天是我和 *戴莹莹* 俩人生中最难忘、最激动、最幸福的时刻。今天我们的长辈、 *道道全公司的领导* 和亲朋好友在百忙中远道而来参加我俩婚礼，给今天的婚礼带来了欢乐，喜悦和祝福。我俩从内心表示感谢！

1. 特别感谢, 湖南道道全公司的领导: 刘建军董事长, 营销总监韩文学先生, 刘永总经理, 杨建斌经理, 杨一经理, 严偌汉经理. 谢谢道道全公司给了我们一家这么好的一个平台, 也给修水老百姓带来了这么好, 这么健康, 这么喜欢的产品.
2. 借着这个机会，我想感谢我的爸爸妈妈, 三十年来的养育之恩。爸爸，妈妈, 我爱您们, 您们辛苦了！
3. 感谢莹莹的爸爸妈妈, 岳父岳母培养出这么优秀的女儿，请放心的把莹莹交给我，我一定不会辜负你们的信任，和莹莹幸福生活一辈子。
4. 感谢修水的和远道而来的亲戚们.
5. 感谢父亲生意上的合作伙伴, 谢谢你们的长期关照
6. 感谢我的大伯对我的关心. 谢谢大伯在爸爸生意上的鼎力帮助, 做了很多的团购活动, 产品的推广

最后，祝大家心想事成、万事如意、幸福与大家同在！


*** 结婚致辞
尊敬的各位来宾：大家好！

今天是我和 *戴莹莹* 俩人生中最难忘、最激动、最幸福的时刻。今天我们的长辈、 *道道全公司的领导* 和亲朋好友在百忙中远道而来参加我俩婚礼仪式，给今天的婚礼带来了欢乐，喜悦和祝福。我俩从内心表示感谢！

- 借着这个机会，我想感谢我的爸爸妈妈, 三十年来的养育之恩。爸爸，妈妈, 我爱您们, 您们辛苦了！
- 感谢莹莹的爸爸妈妈, 岳父岳母培养出这么优秀的女儿，请放心的把莹莹交给我，我一定不会辜负你们的信任，和莹莹幸福生活一辈子。
- 感谢修水的和远道而来的亲戚们. 外婆, 舅舅, 伯伯, 叔叔, 阿姨, 哥哥姐姐弟弟妹妹, 谢谢你们
- 特别感谢, 湖南道道全公司的领导: 刘建军董事长, 营销总监韩文学先生, 刘永总经理, 杨建斌经理, 杨一经理, 严偌汉经理. 谢谢道道全公司给了我们一家这么好的一个平台, 也给修水老百姓带来了这么好, 这么健康, 这么喜欢的产品.
- 感谢父亲生意上的合作伙伴, 谢谢你们的长期关照
- 感谢我的大伯 *龚著兴*, 对我的关心. 我上大学时经常来校园看望我. 谢谢大伯在爸爸生意上的鼎力帮助, 做了很多的团购活动, 产品的推广
- 谢谢弟弟. 我们是亲兄弟

最后，祝大家心想事成、万事如意、幸福与大家同在！


#+BEGIN_HTML
<!--more-->
#+END_HTML

#+BEGIN_LaTeX
  $$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$
#+END_LaTeX

#+begin_src latex :file ../images/orgmode-babel-latex.png :exports results
  \begin{equation}
  \Pr(X_t=j|X_{t-1}=i) = \frac{j(j-1)}{2}\Big(\frac{i}{N}\Big)^j\Big(\frac{N-i}{N}\Big)^{n-j}
  \end{equation}
#+end_src


尊敬的各位领导, 陈府上的外婆母舅等, 各位亲朋好友:
大家中午好!
此时此刻, 我的心情万分激动与开心, 因为今天是我和戴莹莹新婚之日.一时纵有千年万语也难以表达我的内心的喜悦与感激. \\
总之汇聚成两个字,就是"感谢". 首先应感谢"道道全"粮油集团刘董事长以及今天参加我的婚礼的所有嘉宾, 各位领导. \\
在百忙之中亲临我和莹莹的婚典.其次要感谢莹莹的父母, 也就是我最敬爱的岳父岳母大人.将唯一的掌上明珠交给我为终身伴侣. \\
还要感谢我的父母给予我的生命, 多年来给我的付出. 我绝不会辜负大家对我和我的妻子---戴莹莹的关爱与期望! 我们将会用自己勤劳的双手成为世界上最幸福,最快乐的伴侣.
最后, 由衷地祝福各位身体健康. 工作顺利, 万事享通, 阖家幸福.
谢谢大家!
